elephantly_resource:
    resources:
        static_content:
            class: Elephantly\StaticContentBundle\Entity\StaticContent
            form_type: Elephantly\StaticContentBundle\Form\StaticContentType
